### PR TITLE
Legge til proliant dl380 gen11

### PR DESCRIPTION
**Pull request by obimoro**
Legge til proliant dl380 gen11

### CODE REVIEW

**Review by umglurf — CHANGES_REQUESTED** [review]
This belongs in https://github.com/netbox-community/devicetype-library

**Review by sjurtf — APPROVED** [review]

**Comment by sjurtf** [comment]
While I agree that this belongs in the netbox-community repo, I think we should allow it here while we wait for the community repo to accept a PR.

**Comment by umglurf** [comment]
> While I agree that this belongs in the netbox-community repo, I think we should allow it here while we wait for the community repo to accept a PR.

Why? Then we would need to clean up afterwards, which just leads to extra work. Better to just manually import this in our Netbox while waiting for upstream PR accept

**Comment by sjurtf** [comment]
We have discussed internally and agreed that we should keep device-types that belong in the upstream library out of the NRK library.

We do still see value of having a PR process to this repository to try to maintain quality on device types so we would still like to get PRs here - but we will not merge them to master.

We might look into merging them to a separate branch, and automate the process of opening a PR to the upstream library.

We have accepted your PR and imported it to NRKs NetBox manually, but will close this PR without merging it to master.

**Pull request closed without merging**
